# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
  # Si necesitas un administrador de base de datos, puedes descomentar estas líneas
  adminer:
    image: adminer
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
